"""Exact column headers for UPC / DIMS catalog spreadsheet imports."""

UPC_SHEET_NAME = "UPC"
DIMS_SHEET_NAME = "DIMS"

# Exact header order from the source workbook (UPC DIMS.xlsx → UPC sheet).
UPC_HEADERS = [
    "S/C/S",
    "External ID",
    "UPC Code",
    "Vendor Name",
    "Netsuite Style Name",
    "Color Free Form",
    "MPN",
    "Vendor Color Code",
    "SIZE",
    "Season Code",
    "On Hand",
    "On Order",
    "Unit Price",
    "AMZ SOURCING COST",
    "Last Purchase Price",
    "Purchase Price",
    "Average Cost",
    "MSRP",
    "STATUS",
    "Description",
    "Color Holder",
    "Date Created",
    "EXCLUDE FROM AMAZON",
    "EXCLUDE FROM MSW.COM",
    "Website Display Only",
    "Commission Code",
    "Promotion Tag",
    "Merchandise Hierarchy",
    "Gender",
    "Parent",
    "Display Name",
    "Last Modified",
    "Manufacturer",
    "Online Price",
    "Delete Product from BigCommerce",
    "Deleted From MSW.com",
    "Inactive",
    "END OF SEASON",
    "Shipping Override",
    "RFID",
    "EAN",
    "ZOKU STYLE NAME",
    "ZOKU COLOR",
    "PMS-BigCommerce Item Category",
    "Last Markdown Date",
    "Image URL1",
    "External Systems",
    "External Systems [V2]",
    "Amazon Item Sync Error [V2]",
    "AMAZON ERROR/POSTING NOTES",
    "AMAZON BRAND",
    "Fulfilled by Amazon",
    "[ F3 ] Dual Listing",
    "DESC1",
    "DESC2",
    "DESC3",
    "DESC4",
    "DESC5",
    "MAP RELEASE DATE",
    "Bin Number",
]

# Exact header order from the source workbook (UPC DIMS.xlsx → DIMS sheet).
DIMS_HEADERS = [
    "Brand",
    "SKU",
    "UPC #",
    "Description",
    "Current Season",
    "Weight",
    "Volume",
    "Length",
    "Width",
    "Height",
    "CPQ",
    "MC Weight",
    "MC Volume",
    "MC Length",
    "MC Width",
    "MC Height",
    "Item Status",
]

UPC_REQUIRED_HEADER = "UPC Code"
DIMS_REQUIRED_HEADER = "UPC #"
