"""Superadmin Master Sheet generator — enrich uploaded rows from UPC/DIMS catalogs."""
import logging
from pathlib import Path

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile
from fastapi.responses import Response
from supabase import Client

from app.database import get_supabase
from app.dependencies import get_master_sheet_user
from app.middleware.rate_limiter import RateLimits, limiter
from app.services.master_sheet_service import (
    build_master_sheet_template_bytes,
    generate_master_sheet,
)
from app.utils.error_handler import handle_api_errors

logger = logging.getLogger(__name__)

router = APIRouter()

_MAX_BYTES = 25 * 1024 * 1024
_TEMPLATE_DIR = Path(__file__).resolve().parent.parent / "static" / "catalog_templates"


def _validate_xlsx(file: UploadFile) -> None:
    name = (file.filename or "").lower()
    if not name.endswith((".xlsx", ".xlsm", ".xls")):
        raise HTTPException(status_code=400, detail="Upload an .xlsx Master Sheet file.")


@router.get("/master-sheet/template")
@handle_api_errors("download Master Sheet template")
def download_master_sheet_template(current_user: dict = Depends(get_master_sheet_user)):
    path = _TEMPLATE_DIR / "Master_Sheet_Template.xlsx"
    if path.is_file():
        data = path.read_bytes()
    else:
        data = build_master_sheet_template_bytes()
    return Response(
        content=data,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={
            "Content-Disposition": 'attachment; filename="Master_Sheet_Template.xlsx"'
        },
    )


@router.post("/master-sheet/generate", response_model=None)
@limiter.limit(RateLimits.FILE_UPLOAD)
@handle_api_errors("generate Master Sheet")
async def generate_master_sheet_file(
    request: Request,
    file: UploadFile = File(...),
    current_user: dict = Depends(get_master_sheet_user),
    db: Client = Depends(get_supabase),
):
    """Upload Master Sheet input rows; download enriched sheet using UPC + DIMS catalogs."""
    _validate_xlsx(file)
    raw = await file.read()
    if not raw:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")
    if len(raw) > _MAX_BYTES:
        raise HTTPException(status_code=400, detail="File exceeds 25 MB limit.")

    try:
        result = generate_master_sheet(db, file.filename or "upload.xlsx", raw)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    logger.info(
        "Master Sheet generated by %s: rows=%s upc_ok=%s upc_miss=%s mc_upc=%s mc_desc=%s mc_miss=%s",
        current_user.get("email"),
        result.total_rows,
        result.upc_matched,
        result.upc_missing,
        result.mc_matched_by_upc,
        result.mc_matched_by_desc_size,
        result.mc_missing,
    )

    headers = {
        "Content-Disposition": f'attachment; filename="{result.filename}"',
        "X-Master-Total-Rows": str(result.total_rows),
        "X-Master-Upc-Matched": str(result.upc_matched),
        "X-Master-Upc-Missing": str(result.upc_missing),
        "X-Master-Mc-By-Upc": str(result.mc_matched_by_upc),
        "X-Master-Mc-By-Desc-Size": str(result.mc_matched_by_desc_size),
        "X-Master-Mc-Missing": str(result.mc_missing),
    }
    return Response(
        content=result.file_bytes,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers=headers,
    )
